### ISSUE TITLE
Is it able to handel multiple pages ?

### ISSUE THREAD

**Issue by huchenhai** [otigges/pdf-form-to-html#1]
Hi, I'm recently facing the same issue which is letting users edit PDF online.  Your solution is really smart, can this process multiple pages applications? And our PDF forms contain select options which are not covered in the lecture. Please advise, thank you

**Comment by otigges** [comment]
Hi, 

both of your requests (multiple pages and select options) are not covered by this sample. But you  should be able to add these features with some minor additions.

The PDF page number for which you want the image can be set as parameter, see https://github.com/otigges/pdf-form-to-html/blob/deacef010d95b1c8bbacf34516e36a8dd864837a/src/main/java/com/ticesso/pdf/forms/service/FormsRessource.java#L28-L35

For select options you need to enhance the client side JavaScript to render a `<select>` instead of `<input>` for the given field type. And you will need to adapt the PdfFormAnalyzer.fillPdf() method.

**Comment by huchenhai** [comment]
@otigges   hi Oliver, thank you for guiding. Your code is easy to customize, I wrote another function to get how many pages of the pdf file, and get image src in a loop controlled by page numbers. I just simply assign each picture Id to "bgform" object instead of giving class name. And it is working perfectly, all the coordinates are calculated automatically and fitting very well. Thank you very much

**Comment by otigges** [comment]
Hi @huchenhai, I'm happy this works for you. :-)

**Comment by huchenhai** [comment]
@otigges   Hi, I'm trying to place pdf into a bootstrap modal, but offset always wrong due to some weird bootstrap CSS settings. Could you please advice, thank you

**Comment by otigges** [comment]
@huchenhai Hi, sorry, but cannot guess without seeing code or the rendered page what the CSS issue might be. Maybe you find help in a bootstrap forum?
